name: Trigger Airflow DAG

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  trigger-dag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Airflow DAG
        run: |
          curl -X POST ${{ secrets.AIRFLOW_URL }}/api/v1/dags/jenkins_ec2_ml_training_dag/dagRuns \
          -u ${{ secrets.AIRFLOW_USERNAME }}:${{ secrets.AIRFLOW_PASSWORD }} \
          -H "Content-Type: application/json" \
          -d '{
            "conf": {},
            "dag_run_id": "manual_trigger_${{ github.run_id }}",
            "data_interval_end": "${{ env.datetime }}",
            "data_interval_start": "${{ env.datetime }}",
            "logical_date": "${{ env.datetime }}",
            "note": "Manual trigger from GitHub Actions"
          }'
        env:
          AIRFLOW_URL: ${{ secrets.AIRFLOW_URL }}
          AIRFLOW_USERNAME: ${{ secrets.AIRFLOW_USERNAME }}
          AIRFLOW_PASSWORD: ${{ secrets.AIRFLOW_PASSWORD }}
          
